module AppUtils
  def _connection: -> untyped
  def _toggle_base_url : () -> void
  def _auth_provider: -> DarajaAuthProvider

  def _consumer_key: -> string
  def _consumer_secret: -> string
  def _validation_url: -> string
  def _confirmation_url: -> string
  def _is_sandbox: -> bool
end
