module AppUtils
  class BaseConfig
    attr_accessor connection: untyped
    attr_writer is_sandbox: bool

    def toggle_base_url: -> string
  end

  class Default
    def _balance_result_url: -> string
    def _toggle_base_url : () -> void
    def _connection: -> untyped
    def _short_code: -> string
    def _ssl_certificate: -> string
    def _auth_provider: -> DarajaAuthProvider
    def _app_config: -> BaseConfig
    def _consumer_key: -> string
    def _consumer_secret: -> string
    def _validation_url: -> string
    def _confirmation_url: -> string
    def _b2c_result_url: -> string
    def _initiator_name: -> string
    def _initiator_password: -> string
    def _is_sandbox: -> bool
  end
end