name: Ruby

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Test ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.2'
          - '2.7.4'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Linters & Tests
      run: bundle exec rake
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        VALIDATION_URL: ${{ secrets.VALIDATION_URL }}
        CONFIRMATION_URL: ${{ secrets.CONFIRMATION_URL }}
        SHORT_CODE: ${{ secrets.SHORT_CODE }}
        IS_SANDBOX: ${{ secrets.IS_SANDBOX }}
