name: Ruby

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Test ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.2'
          - '2.7.4'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Linters & Tests
      run: bundle exec rake
