name: Release to RubyGems
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-gh:
    runs-on: ubuntu-latest
    name: Setup GitHub
    steps:
      - uses: actions/checkout@v3
      - name: Setup GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ${{ secrets.GITHUB_EMAIL }}
  release:
    needs: setup-gh
    runs-on: ubuntu-latest
    name: Release to RubyGems
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Release to RubyGems
        run: |
          gem install bundler
          bundle install
          bundle exec rake release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}